import './GameLog.css'
export default function GameLog({ turns }) {
  //This needs info generated by a GameBoard, so we LIFT STATE UP AGAIN
  return (
    <ol id="log">
      {turns.map((turn) => (
        //Template Literal syntax allows us to return a string of two dynamic values such as below
        //Great for dynamically generating long keys abstractly
        <li key={`${turn.square.row}${turn.square.col}`}>
          {turn.player} selected {turn.square.row}, {turn.square.col}
        </li>
      ))}
    </ol>
  );
}
